spring:
    application:
        name: library-application
    datasource:
        url: jdbc:postgresql://localhost:5433/library_application
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
server:
    port: 8081